name: modernize
on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Execution mode"
        required: true
        default: "fix"
        type: choice
        options:
          - fix
          - check
permissions:
  contents: write
  pull-requests: write
jobs:
  modernize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alesr/gomodern@v1
        with:
          mode: ${{ inputs.mode || 'fix' }}
          create-pr: "true"
